# Generated by Django 5.0.4 on 2024-05-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_likes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created", "-updated"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
